---
name: Check for new usages of deprecated functionality
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: ./scripts/run-gradually-deprecated.sh
