---
name: Pull Request New Commit

on:
  pull_request:
    types: [synchronize]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: waiting-response