---
name: Pull Request New Commit

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [synchronize]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: waiting-response
