---
name: Terraform Schema Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

concurrency:
  group: 'tflint-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make tflint
