---
name: Unit Tests

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/unit-test.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make test
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
      - name: Add waiting-response on fail
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: waiting-response
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          repo: ${{ github.event.repository.full_name }}
