---
name: Validate Examples

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/validate-examples.yaml'
      - 'examples/**'

concurrency:
  group: 'examples-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  website-lint:
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make validate-examples
      - name: Add waiting-response on fail
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: waiting-response
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          repo: ${{ github.event.repository.full_name }}
