---
name: Website Linting

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - ".github/workflows/website-lint.yaml"
      - "website/**"

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make website-lint
      - name: Add waiting-response on fail
        if: failure()
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: waiting-response
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          repo: ${{ github.event.repository.full_name }}